name: Cron E2E - Ramparts

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 1:30 AM UTC = 7:00 AM IST
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  javelin-e2e:
    needs:
      - javelin-env
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build for integration tests
        run: cargo build --release

      - name: Run integration tests
        run: |
          # Test CLI help
          ./target/release/rampart --help
          
          # Test init-config command
          ./target/release/rampart init-config --force
          
          # Test server startup (timeout after 5 seconds)
          timeout 5s ./target/release/rampart server --port 3000 || true