name: Cron E2E - Ramparts

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 1:30 AM UTC = 7:00 AM IST

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  javelin-e2e:
    needs:
      - javelin-env
    permissions:
      contents: 'read'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setting up the Crate Version
        env:
          CARGO_VER_FILE: "Cargo.toml"
          RELEASE_NAME: ${{ github.event.release.name }}
        shell: bash
        run: |-
          export RELEASE_VERSION="v0.0.1"
          if cat ${{ env.CARGO_VER_FILE }} | grep 'version = "RELEASE_VERSION"' ; then
            sed -i "s|^version = \"RELEASE_VERSION\"|version = \"${RELEASE_VERSION}\"|g" ${{ env.CARGO_VER_FILE }}
            cat ${file}
          else
            echo "Version entry format is wrong in the ${{ env.CARGO_VER_FILE }} file...!"
            cat ${file}
            exit 1
          fi

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build for integration tests
        run: cargo build --release

      - name: Run integration tests
        run: |
          # Test CLI help
          ./target/release/rampart --help
          
          # Test init-config command
          ./target/release/rampart init-config --force
          
          # Test server startup (timeout after 5 seconds)
          timeout 5s ./target/release/rampart server --port 3000 || true